apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api
  template:
    metadata:
      labels:
        app: k8s-api
    spec:
      containers:
      - name: k8s-api
        image: your-dockerhub-username/k8s-api
        ports:
        - containerPort: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api-service
spec:
  selector:
    app: k8s-api
  ports:
  - protocol: TCP
    port: 5010
    targetPort: 5010
  type: ClusterIP
